name: Build Linux Game with SDL2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y build-essential git libsdl2-dev

      - name: Compile the Linux game
        run: |
          mkdir -p build
          cd build
          clang -o MyGame ../main.c \
            -lSDL2

      - name: Upload the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-game
          path: build/MyGame
