name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SDL2
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf

      - name: Find SDL2 path
        run: |
          echo "SDL2 installed at:" $(brew --prefix sdl2)
          ls $(brew --prefix sdl2)/include/SDL2

      - name: Compile the iOS App
        run: |
          mkdir -p build
          SDL2_PATH=$(brew --prefix sdl2)
          clang -o build/MyIOSApp main.c -I$SDL2_PATH/include/SDL2 -L$SDL2_PATH/lib -lSDL2 -framework UIKit -framework Foundation -framework CoreGraphics

      - name: Upload the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/MyIOSApp
